### ISSUE TITLE
PPlus implementation identical to PStar

### ISSUE THREAD

**Issue by ColinH** [MoserMichael/cppcombinator#1]
https://github.com/MoserMichael/cppcombinator/blob/18b1720ba0e359ac1fda98e627c374896c738008/inc/parse.h#L899

The implementation of `PPlus` is identical to that of `PStar`, and the comments both say "zero or more", however the documentation correctly says "one or more" for `PPlus`. Looks like a copy-n-paste error in the code.

**Comment by MoserMichael** [comment]
thanks! fixed.
